### ISSUE TITLE
Error on Windows 7

### ISSUE THREAD

**Issue by pedrodj** [m4ll0k/WAScan#10]
Hi m4ll0k,

thank you for your work ;)

I have problems on Windows 7 running Spaghetti
****
Spaghetti-master>spaghetti.py
Traceback (most recent call last):
  File "Spaghetti-master\spaghetti.py", line 24, in <module>
    from modules.discovery.disclosure import disclosure
  File "Spaghetti-master\modules\discovery\disclosure\disclosure.py", line 11, in <module>
    import ip
  File "Spaghetti-master\modules\discovery\disclosure\ip.py", line 11, in <module>
    from extractor import ip
  File "Spaghetti-master\extractor\ip.py", line 13, in <module>
    from parser import parse
ImportError: cannot import name parse

Spaghetti-master>
****
but all requirements seems installed
****
Spaghetti-master>pip install -r requirements.txt
Requirement already satisfied: requests in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: BeautifulSoup in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests->-r requirements.tx
t (line 1))
Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests->-r requirements.txt (line
 1))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests->-r requirements.tx
t (line 1))
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests->-r requirements.txt (
line 1))
****
Some suggestion ?
I'm using Windows 7 ultimate, updated and python 2,7.

Thank you

**Comment by m4ll0k** [comment]
Do not use curl to download Spaghetti!!

**Comment by pedrodj** [comment]
I haven't used curl: downloaded directly form github, unzipped and done ;)

**Comment by m4ll0k** [comment]
try with `pip install requests`

**Comment by pedrodj** [comment]
Spaghetti-master>pip install -r requirements.txt
Requirement already satisfied: requests in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: BeautifulSoup in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests->-r requirements.tx
t (line 1))
Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests->-r requirements.txt (line
1))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests->-r requirements.tx
t (line 1))
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests->-r requirements.txt (
line 1))

but it doesn't run properly than ;)

**Comment by dadokkio** [comment]
I've the same problem on windows7 with the following environment:

```
(py2) Spaghetti-master>pip list --forma=legacy
BeautifulSoup (3.2.1)
certifi (2017.7.27.1)
chardet (3.0.4)
idna (2.6)
pip (9.0.1)
requests (2.18.4)
setuptools (36.4.0)
urllib3 (1.22)
wheel (0.29.0)
wincertstore (0.2)
```

**Comment by dadokkio** [comment]
I had to rename parser folder and change the two relative imports and now it's working.

**Comment by pedrodj** [comment]
Can you explain me ?

**Comment by dadokkio** [comment]
[parser is a standard module in python](https://docs.python.org/2/library/parser.html) so it tried to import parse function from there.
I've just renamed parser folder to sp_parser and edited the two import.

This picture should be explicative:

![image](https://user-images.githubusercontent.com/355183/30704059-c3a360e6-9ef1-11e7-8072-240858e5a2bd.png)

**Comment by pedrodj** [comment]
So I have to edit the file ?

**Comment by pedrodj** [comment]
Seem fixed in latest release ;)
