### ISSUE TITLE
cannot import name parse

### ISSUE THREAD

**Issue by j3ers3** [m4ll0k/WAScan#15]
from parser import parse
ImportError: cannot import name parse

**Comment by fuuddanni** [comment]
me too in virtualenv, all requirements are satisfied.

(spaghetti) E:\Github\Spaghettiworkon>cat requirements.txt
requests
BeautifulSoup
(spaghetti) E:\Github\Spaghettiworkon>pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\besitzer\envs\spaghetti\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: BeautifulSoup in c:\users\besitzer\envs\spaghetti\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\besitzer\envs\spaghetti\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: certifi>=2017.4.17 in c:\users\besitzer\envs\spaghetti\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\besitzer\envs\spaghetti\lib\site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\besitzer\envs\spaghetti\lib\site-packages (from requests->-r requirements.txt (line 1))

(spaghetti) E:\Github\Spaghettiworkon>spaghetti.py --help
Traceback (most recent call last):
  File "E:\Github\Spaghettiworkon\spaghetti.py", line 24, in <module>
    from modules.discovery.disclosure import disclosure
  File "E:\Github\Spaghettiworkon\modules\discovery\disclosure\disclosure.py", line 11, in <module>
    import ip
  File "E:\Github\Spaghettiworkon\modules\discovery\disclosure\ip.py", line 11, in <module>
    from extractor import ip
  File "E:\Github\Spaghettiworkon\extractor\ip.py", line 13, in <module>
    from parser import parse
ImportError: cannot import name parse

**Comment by dadokkio** [comment]
see issue #10
