### ISSUE TITLE
Unusually high number of false positives

### ISSUE THREAD

**Issue by Viss** [m4ll0k/WAScan#18]
I attempted to use this tool against a site that has redirects for files that arent there, and it claimed that it found many many files and directories that didn't actually exist.

It appears as though the tool is not examining http return headers, and missing things like 301 redirects, and location headers which redirect the browser. 

Try it against fusion.net, and you'll see what i mean. Then try one or two of the results with curl -v.

**Comment by m4ll0k** [comment]
`--redirect False`

**Comment by Viss** [comment]
i tried this just now on the same domain, there are still a ton of false positives.
i encourage you to try it.
