### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by pedrodj** [m4ll0k/WAScan#23]
Hi m4ll0k,

as always thank you for you work.

I have problems scanning site with SSL certificate
***
connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings  InsecureRequestWarning)
***

Any help ?

Thank you ;)

**Comment by m4ll0k** [comment]
try the new version

**Comment by pedrodj** [comment]
Installed the last one released today before opening this ticket, the error is still here ;)

Regards

**Comment by m4ll0k** [comment]
![scree](https://i.imgur.com/LrTPo0g.png)

**Comment by pedrodj** [comment]
Have it to add these 2 lines to request.py?

Regards

**Comment by m4ll0k** [comment]
yeap

**Comment by pedrodj** [comment]
Thank you man :P

**Comment by pedrodj** [comment]
![image](https://user-images.githubusercontent.com/11228452/31629356-aa4a6722-b2b3-11e7-9c87-15aa7fe70422.png)


Error still here :\

**Comment by m4ll0k** [comment]
You have `urllib3` installed?

**Comment by pedrodj** [comment]
E:\Python27\Spaghetti-master>pip install urllib3
Requirement already satisfied: urllib3 in c:\python27\lib\site-packages

**Comment by livtyler** [comment]
I also added these lines and it also have urllib3 installed I have same error still.

**Comment by pedrodj** [comment]
Problem still here even I have updated to the latest release.

Thank you

**Comment by mlinton** [comment]
use the following syntax to ignore it for now:
`python -W ignore spaghetti.py`

**Comment by gopinath6** [comment]
May i know if any permanent fix available for  this error?

InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html

Have installed urllib3 also
