### ISSUE TITLE
Providing Docker image for convenience

### ISSUE THREAD

**Issue by andromedarabbit** [m4ll0k/WAScan#24]
``` 
FROM python:2.7-onbuild

CMD ["python", "spaghetti.py"]
```

Simple Dockerfile should be enough, I believe. It might be better if you provide the official Docker image through Docker Hub.

Thanks for the great tool.

**Comment by m4ll0k** [comment]
ok

**Comment by bkimminich** [comment]
Any chance the Docker image is coming soon? This should do the trick as a `Dockerfile`, I think:

```
FROM python:2.7-onbuild
RUN pip install BeautifulSoup

CMD ["python", "wascan.py"]
```
