### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by SpongeCrafted** [m4ll0k/WAScan#25]
Just installed it with the requirements, and I get an Invalid Syntax error.

>   File "spaghetti.py", line 37
>     except getopt.error,e:
>                        ^
> SyntaxError: invalid syntax

**Comment by andongzhang1991** [comment]
Maybe you use python3.x ,this project must be use python 2.7+ ,because the requirement.txt file install BeautifulSoup ,but python3.x just can install BeautifulSoup4
