### ISSUE TITLE
ImportError: No module named BeautifulSoup

### ISSUE THREAD

**Issue by gemalandaverde** [m4ll0k/WAScan#41]
$ python wascan.py --verbose --url http://www.WESBITE.co.uk --scan 1
Traceback (most recent call last):
  File "wascan.py", line 36, in <module>
    from lib.handler.crawler import *
  File "/Users/gemalandaverde/WAScan/lib/handler/crawler.py", line 10, in <module>
    from lib.request.crawler import SCrawler
  File "/Users/gemalandaverde/WAScan/lib/request/crawler.py", line 15, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

**Comment by codingo** [comment]
The error is indicating to you that you need to install the BeautifulSoup library. You can do this by running:

```
pip install BeautifulSoup
```

This also indicates that you didn't follow the setup instructions on the main page of the repository, you should go back to the root of the directory and run:

```
pip install -r requirements.txt
```

This will install all necessary dependencies for you to use WAScan.

**Comment by Aseyed** [comment]
Use this:
``pip install BeautifulSoup4``
Then edit this file `WAScan/lib/request/crawler.py` whit this:
`from bs4 import BeautifulSoup`
Now you can run whit `python wascan.py`

**Comment by zhymer96** [comment]
Requirement already satisfied: BeautifulSoup in /usr/lib/python2.7/dist-packages  :(
i got :
 File "wascan.py", line 118, in <module>
    wascan().main()
  File "wascan.py", line 110, in main
    FullScan(kwargs,u,kwargs['data'])
