### ISSUE TITLE
indexError

### ISSUE THREAD

**Issue by soupnatzi** [m4ll0k/WAScan#54]
Traceback (most recent call last):
  File "wascan.py", line 118, in <module>
    wascan().main()
  File "wascan.py", line 91, in main
    Attacks(kwargs,url,kwargs['data'])
  File "/root/scanner/wascan/lib/handler/attacks.py", line 24, in Attacks
    module(kwargs,url,data).run()
  File "/root/scanner/wascan/plugins/attacks/htmli.py", line 49, in run
    for url in urls.run():
  File "/root/scanner/wascan/lib/utils/params.py", line 75, in run
    self.get()
  File "/root/scanner/wascan/lib/utils/params.py", line 55, in get
    params = self.url.split("?")[1].split("&")
IndexError: list index out of range

**Comment by Rzqu** [comment]
I also have this issue when trying to run with --scan 1

**Comment by codingo** [comment]
@soupnatzi @Rzqu although the stacktrace is useful can you also include the flags that you used? It's difficult to reproduce this in its current form.

**Comment by Rzqu** [comment]
Hi @codingo This is what i am running before it throws the error

![image](https://user-images.githubusercontent.com/39829605/45949184-f51b5480-bff2-11e8-885b-b7a20d4db5fb.png)

**Comment by m4ll0k** [comment]
`--scan` options 1 need parameters:
Example:
` python wascan.py --url http://www.site.com/index.php?id=1 --scan 1`

**Comment by teddyzhai** [comment]
Hi @m4ll0k , can you pls detail what parameter does the command need here? thanks a lot.

**Comment by shreyaspg** [comment]
Hey so it's not a code error, the logic of code expects the post data , I'd recommend using something like this

python wascan.py --url https://somewebsite.com/loginpath -d "username=something&password=else" --scan 1

the data is passed using the -d arg, so go inspect the name of the form fields on the target site ,in my case it was username and password.

**Comment by tanaydin** [comment]
please check https://github.com/m4ll0k/WAScan/pull/80
