### ISSUE TITLE
Got error on Mac

### ISSUE THREAD

**Issue by adtdandis** [m4ll0k/WAScan#58]
I already get BeautifulSoup installed:

pip install BeautifulSoup
Requirement already satisfied: BeautifulSoup in /usr/local/lib/python2.7/site-packages (3.2.1)

but once running 
wascan.py --url https://xxxxx.com .          

 I got the following:

 File "wascan.py", line 37, in <module>
    from lib.handler.crawler import *
  File "/Users/XXX/Downloads/WAScan/lib/handler/crawler.py", line 10, in <module>
    from lib.request.crawler import SCrawler
  File "/Users/XXXXX/Downloads/WAScan/lib/request/crawler.py", line 15, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

**Comment by m4ll0k** [comment]
try with `pip install bs4` or `apt-get install python-bs4`

**Comment by jaba0x** [comment]
> try with `pip install bs4` or `apt-get install python-bs4`

pip did the job! thanks
