### ISSUE TITLE
 Error: <urlopen error ('_ssl.c:711: The handshake operation timed out',)

### ISSUE THREAD

**Issue by filebe777** [m4ll0k/WAScan#64]
[+] Starting: 14/12/2018 at 06:34:03

[i] Starting full scan module...
[i] Starting fingerprint target...
[+] Server: Apache
[+] Language: PHP
[+] Cookie without Secure flag set
[+] Cookie without HttpOnly flag set
[+] Session Cookie are valid only on that Path: /
[+] Cookie Header contains multiple cookies
[+] X-XSS-Protection header missing
[+] Strict-Transport-Security header missing
[+] X-Content-Type-Options header missing
[+] Uncommon header "x-frame-options" found, with contents: SAMEORIGIN
[i] Starting crawler...
[!] Error: <urlopen error ('_ssl.c:711: The handshake operation timed out',)>

**Comment by calvinbcoding** [comment]
When I run speedtest-cli (which I installed via Homebrew) I get the "[!] Error: <urlopen error ('_ssl.c:711: The handshake operation timed out',)>" error. Has any progress been made on this issue?

**Comment by rajeshk28** [comment]
same issue
