### ISSUE TITLE
The code that caused this warning is on line 118

### ISSUE THREAD

**Issue by Hisoka503** [m4ll0k/WAScan#70]
The code that caused this warning is on line 118 of the file wascan.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))
[!] Error: <urlopen error timed out>

**Comment by jordantsap** [comment]
Have the same exact error, any solution??

**Comment by MrH0wl** [comment]
Open **WAScan/lib/request/crawler.py**

Then change line 71 to this: soup = BeautifulSoup(self.content, 'lxml')
