### ISSUE TITLE
Starting crawler... [!] Error: timed out

### ISSUE THREAD

**Issue by jordantsap** [m4ll0k/WAScan#85]
when i run wascan --url http://www.website.gr/?pid=1&la=1
i get this [1] 5400 What is it??

and then i get
$/home/user/.local/lib/python2.7/site-packages/BeautifulSoup.py:114: UserWarning: You are using a very old release of Beautiful Soup, last updated in 2011. If you installed the 'beautifulsoup' package through pip, you should know the 'beautifulsoup' package name is about to be reclaimed by a more recent version of Beautiful Soup which is incompatible with this version.

This will happen at some point after January 1, 2021.

If you just started this project, this is easy to fix. Install the 'beautifulsoup4' package instead of 'beautifulsoup' and start using Beautiful Soup 4.

If this is an existing project that depends on Beautiful Soup 3, the project maintainer (potentially you) needs to start the process of migrating to Beautiful Soup 4. This should be a relatively easy part of the Python 3 migration.

  """)

**Comment by m4ll0k** [comment]
I'm writing a new version!
