### ISSUE TITLE
Upgrade for python 3.x

### ISSUE THREAD

**Issue by UbuntuEvangelist** [m4ll0k/WAScan#87]
You are using a very old release of Beautiful Soup, last updated in 2011. If you installed the 'beautifulsoup' package through pip, you should know the 'beautifulsoup' package name is about to be reclaimed by a more recent version of Beautiful Soup which is incompatible with this version.

This will happen at some point after January 1, 2021.

If you just started this project, this is easy to fix. Install the 'beautifulsoup4' package instead of 'beautifulsoup' and start using Beautiful Soup 4.

If this is an existing project that depends on Beautiful Soup 3, the project maintainer (potentially you) needs to start the process of migrating to Beautiful Soup 4. This should be a relatively easy part of the Python 3 migration.

![Screenshot from 2020-04-19 16-24-14](https://user-images.githubusercontent.com/1058663/79685400-67e5c380-825a-11ea-9fe6-24821e08880e.png)

**Comment by m4ll0k** [comment]
i'm writing a new version @UbuntuEvangelist
