### ISSUE TITLE
The code that caused this warning is on line 71 of the file /root/tools/wascan/lib/request/crawler.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.    soup = BeautifulSoup(self.content)

### ISSUE THREAD

**Issue by subhash0x** [m4ll0k/WAScan#90]
The code that caused this warning is on line 71 of the file /root/tools/wascan/lib/request/crawler.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(self.content)

**Comment by S-Ch22** [comment]
I had the same problem. Added the argument given on the file mentioned (crawler.py) and was solved
